In [5]:
#Learning Pandas & pylab

In [68]:
%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas
from pandas import *
from sklearn import datasets, linear_model

In [32]:
houses = read_csv('home_data.csv')

In [42]:
houses

            id             date    price  bedrooms  bathrooms  sqft_living  \
0   7129300520  20141013T000000   221900         3       1.00         1180
1   6414100192  20141209T000000   538000         3       2.25         2570
2   5631500400  20150225T000000   180000         2       1.00          770
3   2487200875  20141209T000000   604000         4       3.00         1960
4   1954400510  20150218T000000   510000         3       2.00         1680
5   7237550310  20140512T000000  1225000         4       4.50         5420
6   1321400060  20140627T000000   257500         3       2.25         1715
7   2008000270  20150115T000000   291850         3       1.50         1060
8   2414600126  20150415T000000   229500         3       1.00         1780
9   3793500160  20150312T000000   323000         3       2.50         1890
10  1736800520  20150403T000000   662500         3       2.50         3560
11  9212900260  20140527T000000   468000         2       1.00         1160
12   114101516  20140528T000000   310000         3       1.00         1430
13  6054650070  20141007T000000   400000         3       1.75         1370
14  1175000570  20150312T000000   530000         5       2.00         1810
15  9297300055  20150124T000000   650000         4       3.00         2950
16  1875500060  20140731T000000   395000         3       2.00         1890
17  6865200140  20140529T000000   485000         4       1.00         1600
18    16000397  20141205T000000   189000         2       1.00         1200
19  7983200060  20150424T000000   230000         3       1.00         1250
20  6300500875  20140514T000000   385000         4       1.75         1620
21  2524049179  20140826T000000  2000000         3       2.75         3050
22  7137970340  20140703T000000   285000         5       2.50         2270
23  8091400200  20140516T000000   252700         2       1.50         1070
24  3814700200  20141120T000000   329000         3       2.25         2450
25  1202000200  20141103T000000   233000         3       2.00         1710
26  1794500383  20140626T000000   937000         3       1.75         2450
27  3303700376  20141201T000000   667000         3       1.00         1400
28  5101402488  20140624T000000   438000         3       1.75         1520
29  1873100390  20150302T000000   719000         4       2.50         2570
30  8562750320  20141110T000000   580500         3       2.50         2320
31  2426039314  20141201T000000   280000         2       1.50         1190
32   461000390  20140624T000000   687500         4       1.75         2330
33  7589200193  20141110T000000   535000         3       1.00         1090
34  7955080270  20141203T000000   322500         4       2.75         2060
35  9547205180  20140613T000000   696000         3       2.50         2300
36  9435300030  20140528T000000   550000         4       1.00         1660
37  2768000400  20141230T000000   640000         4       2.00         2360
38  7895500070  20150213T000000   240000         4       1.00         1220
39  2078500320  20140620T000000   605000         4       2.50         2620
40  5547700270  20140715T000000   625000         4       2.50         2570
41  7766200013  20140811T000000   775000         4       2.25         4220
42  7203220400  20140707T000000   861990         5       2.75         3595
43  9270200160  20141028T000000   685000         3       1.00         1570
44  1432701230  20140729T000000   309000         3       1.00         1280
45  8035350320  20140718T000000   488000         3       2.50         3160
46  8945200830  20150325T000000   210490         3       1.00          990
47  4178300310  20140716T000000   785000         4       2.50         2290
48  9215400105  20150428T000000   450000         3       1.75         1250
49   822039084  20150311T000000  1350000         3       2.50         2753
50  5245600105  20140916T000000   228000         3       1.00         1190
51  7231300125  20150217T000000   345000         5       2.50         3150
52  7518505990  20141231T000000   600000         3       1.75         1410
53  3626039271  20150205T000000   585000         2       1.75         1980
54  4217401195  20150303T000000   920000         5       2.25         2730
55  9822700295  20140512T000000   885000         4       2.50         2830
56  9478500640  20140819T000000   292500         4       2.50         2250
57  2799800710  20150407T000000   301000         3       2.50         2420
58  7922800400  20140827T000000   951000         5       3.25         3250
59  8079040320  20150223T000000   430000         4       3.00         1850
           ...              ...      ...       ...        ...          ...

    sqft_lot  floors  waterfront  view  condition  grade  sqft_above  \
0       5650     1.0           0     0          3      7        1180
1       7242     2.0           0     0          3      7        2170
2      10000     1.0           0     0          3      6         770
3       5000     1.0           0     0          5      7        1050
4       8080     1.0           0     0          3      8        1680
5     101930     1.0           0     0          3     11        3890
6       6819     2.0           0     0          3      7        1715
7       9711     1.0           0     0          3      7        1060
8       7470     1.0           0     0          3      7        1050
9       6560     2.0           0     0          3      7        1890
10      9796     1.0           0     0          3      8        1860
11      6000     1.0           0     0          4      7         860
12     19901     1.5           0     0          4      7        1430
13      9680     1.0           0     0          4      7        1370
14      4850     1.5           0     0          3      7        1810
15      5000     2.0           0     3          3      9        1980
16     14040     2.0           0     0          3      7        1890
17      4300     1.5           0     0          4      7        1600
18      9850     1.0           0     0          4      7        1200
19      9774     1.0           0     0          4      7        1250
20      4980     1.0           0     0          4      7         860
21     44867     1.0           0     4          3      9        2330
22      6300     2.0           0     0          3      8        2270
23      9643     1.0           0     0          3      7        1070
24      6500     2.0           0     0          4      8        2450
25      4697     1.5           0     0          5      6        1710
26      2691     2.0           0     0          3      8        1750
27      1581     1.5           0     0          5      8        1400
28      6380     1.0           0     0          3      7         790
29      7173     2.0           0     0          3      8        2570
30      3980     2.0           0     0          3      8        2320
31      1265     3.0           0     0          3      7        1190
32      5000     1.5           0     0          4      7        1510
33      3000     1.5           0     0          4      8        1090
34      6659     1.0           0     0          3      7        1280
35      3060     1.5           0     0          3      8        1510
36     34848     1.0           0     0          1      5         930
37      6000     2.0           0     0          4      8        2360
38      8075     1.0           0     0          2      7         890
39      7553     2.0           0     0          3      8        2620
40      5520     2.0           0     0          3      9        2570
41     24186     1.0           0     0          3      8        2600
42      5639     2.0           0     0          3      9        3595
43      2280     2.0           0     0          3      7        1570
44      9656     1.0           0     0          4      6         920
45     13603     2.0           0     0          3      8        3160
46      8528     1.0           0     0          3      6         990
47     13416     2.0           0     0          4      9        2290
48      5963     1.0           0     0          4      7        1250
49     65005     1.0           1     2          5      9        2165
50      9199     1.0           0     0          3      7        1190
51      9134     1.0           0     0          4      8        1640
52      4080     1.0           0     0          4      7        1000
53      8550     1.0           0     0          3      7         990
54      6000     1.5           0     0          3      8        2130
55      5000     2.0           0     0          3      9        2830
56      4495     2.0           0     0          3      7        2250
57      4750     2.0           0     0          3      8        2420
58     14342     2.0           0     4          4      8        3250
59      9976     2.0           0     0          3      8        1850
         ...     ...         ...   ...        ...    ...         ...

    sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0               0      1955             0    98178  47.5112 -122.257
1             400      1951          1991    98125  47.7210 -122.319
2               0      1933             0    98028  47.7379 -122.233
3             910      1965             0    98136  47.5208 -122.393
4               0      1987             0    98074  47.6168 -122.045
5            1530      2001             0    98053  47.6561 -122.005
6               0      1995             0    98003  47.3097 -122.327
7               0      1963             0    98198  47.4095 -122.315
8             730      1960             0    98146  47.5123 -122.337
9               0      2003             0    98038  47.3684 -122.031
10           1700      1965             0    98007  47.6007 -122.145
11            300      1942             0    98115  47.6900 -122.292
12              0      1927             0    98028  47.7558 -122.229
13              0      1977             0    98074  47.6127 -122.045
14              0      1900             0    98107  47.6700 -122.394
15            970      1979             0    98126  47.5714 -122.375
16              0      1994             0    98019  47.7277 -121.962
17              0      1916             0    98103  47.6648 -122.343
18              0      1921             0    98002  47.3089 -122.210
19              0      1969             0    98003  47.3343 -122.306
20            760      1947             0    98133  47.7025 -122.341
21            720      1968             0    98040  47.5316 -122.233
22              0      1995             0    98092  47.3266 -122.169
23              0      1985             0    98030  47.3533 -122.166
24              0      1985             0    98030  47.3739 -122.172
25              0      1941             0    98002  47.3048 -122.218
26            700      1915             0    98119  47.6386 -122.360
27              0      1909             0    98112  47.6221 -122.314
28            730      1948             0    98115  47.6950 -122.304
29              0      2005             0    98052  47.7073 -122.110
30              0      2003             0    98027  47.5391 -122.070
31              0      2005             0    98133  47.7274 -122.357
32            820      1929             0    98117  47.6823 -122.368
33              0      1929             0    98117  47.6889 -122.375
34            780      1981             0    98058  47.4276 -122.157
35            790      1930          2002    98115  47.6827 -122.310
36            730      1933             0    98052  47.6621 -122.132
37              0      1904             0    98107  47.6702 -122.362
38            330      1969             0    98001  47.3341 -122.282
39              0      1996             0    98056  47.5301 -122.180
40              0      2000             0    98074  47.6145 -122.027
41           1620      1984             0    98166  47.4450 -122.347
42              0      2014             0    98053  47.6848 -122.016
43              0      1922             0    98119  47.6413 -122.364
44            360      1959             0    98058  47.4485 -122.175
45              0      2003             0    98019  47.7443 -121.977
46              0      1966             0    98023  47.3066 -122.371
47              0      1981             0    98007  47.6194 -122.151
48              0      1953             0    98115  47.6796 -122.301
49            588      1953             0    98070  47.4041 -122.451
50              0      1955             0    98148  47.4258 -122.322
51           1510      1966             0    98056  47.4934 -122.189
52            410      1950             0    98117  47.6808 -122.384
53            990      1981             0    98117  47.6989 -122.369
54            600      1927             0    98105  47.6571 -122.281
55              0      1995             0    98105  47.6597 -122.290
56              0      2008             0    98042  47.3663 -122.114
57              0      2003             0    98042  47.3663 -122.122
58              0      1968             0    98008  47.5880 -122.116
59              0      1991             0    98059  47.5059 -122.149
              ...       ...           ...      ...      ...      ...

    sqft_living15
0            1340 ...
1            1690 ...
2            2720 ...
3            1360 ...
4            1800 ...
5            4760 ...
6            2238 ...
7            1650 ...
8            1780 ...
9            2390 ...
10           2210 ...
11           1330 ...
12           1780 ...
13           1370 ...
14           1360 ...
15           2140 ...
16           1890 ...
17           1610 ...
18           1060 ...
19           1280 ...
20           1400 ...
21           4110 ...
22           2240 ...
23           1220 ...
24           2200 ...
25           1030 ...
26           1760 ...
27           1860 ...
28           1520 ...
29           2630 ...
30           2580 ...
31           1390 ...
32           1460 ...
33           1570 ...
34           2020 ...
35           1590 ...
36           2160 ...
37           1730 ...
38           1290 ...
39           2620 ...
40           2470 ...
41           2410 ...
42           3625 ...
43           1580 ...
44           1340 ...
45           3050 ...
46           1228 ...
47           2680 ...
48            970 ...
49           2680 ...
50           1190 ...
51           1990 ...
52           1410 ...
53           1480 ...
54           2730 ...
55           1950 ...
56           2250 ...
57           2690 ...
58           2960 ...
59           2270 ...
              ...

[21613 rows x 21 columns]

In [43]:
exp_houses = houses[houses.zipcode == 98039]

In [45]:
exp_houses.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,
2974,3625049014,20140829T000000,2950000,4,3.5,4860,23885,2,0,0,3,12,4860,0,1996,0,98039,47.6172,-122.230,3580,...
3761,2540700110,20150212T000000,1905000,4,3.5,4210,18564,2,0,0,3,11,4210,0,2001,0,98039,47.6206,-122.225,3520,...
4077,3262300940,20141107T000000,875000,3,1.0,1220,8119,1,0,0,4,7,1220,0,1955,0,98039,47.6328,-122.236,1910,...
4078,3262300940,20150210T000000,940000,3,1.0,1220,8119,1,0,0,4,7,1220,0,1955,0,98039,47.6328,-122.236,1910,...
4149,6447300265,20141014T000000,4000000,4,5.5,7080,16573,2,0,0,3,12,5760,1320,2008,0,98039,47.6151,-122.224,3140,...

In [54]:
avg_price = exp_houses['price'].mean(axis=1)

In [55]:
avg_price

2160606.6000000001

In [62]:
mask1 = ((houses['sqft_living'] > 2000) & (houses['sqft_living'] <= 4000))

In [63]:
filter_houses1= houses[mask1]

In [64]:
filter_houses1

             id             date    price  bedrooms  bathrooms  sqft_living  \
1    6414100192  20141209T000000   538000         3       2.25         2570
10   1736800520  20150403T000000   662500         3       2.50         3560
15   9297300055  20150124T000000   650000         4       3.00         2950
21   2524049179  20140826T000000  2000000         3       2.75         3050
22   7137970340  20140703T000000   285000         5       2.50         2270
24   3814700200  20141120T000000   329000         3       2.25         2450
26   1794500383  20140626T000000   937000         3       1.75         2450
29   1873100390  20150302T000000   719000         4       2.50         2570
30   8562750320  20141110T000000   580500         3       2.50         2320
32    461000390  20140624T000000   687500         4       1.75         2330
34   7955080270  20141203T000000   322500         4       2.75         2060
35   9547205180  20140613T000000   696000         3       2.50         2300
37   2768000400  20141230T000000   640000         4       2.00         2360
39   2078500320  20140620T000000   605000         4       2.50         2620
40   5547700270  20140715T000000   625000         4       2.50         2570
42   7203220400  20140707T000000   861990         5       2.75         3595
45   8035350320  20140718T000000   488000         3       2.50         3160
47   4178300310  20140716T000000   785000         4       2.50         2290
49    822039084  20150311T000000  1350000         3       2.50         2753
51   7231300125  20150217T000000   345000         5       2.50         3150
54   4217401195  20150303T000000   920000         5       2.25         2730
55   9822700295  20140512T000000   885000         4       2.50         2830
56   9478500640  20140819T000000   292500         4       2.50         2250
57   2799800710  20150407T000000   301000         3       2.50         2420
58   7922800400  20140827T000000   951000         5       3.25         3250
60   1516000055  20141210T000000   650000         3       2.25         2150
62   5072410070  20141021T000000   505000         3       1.75         2519
65   3253500160  20141120T000000   317625         3       2.75         2770
66   3394100030  20140909T000000   975000         4       2.50         2720
67   3717000160  20141009T000000   287000         4       2.50         2240
69   1802000060  20140612T000000  1325000         5       2.25         3200
72   8820901275  20140610T000000   571000         4       2.00         2750
73   5416510140  20140710T000000   360000         4       2.50         2380
75   3276920270  20141105T000000   832500         4       4.00         3430
79   1531000030  20150323T000000   720000         4       2.50         3450
80   5104520400  20141202T000000   390000         3       2.50         2350
82   9418400240  20141028T000000   355000         2       1.00         2020
85   4232902595  20141114T000000   940000         3       1.50         2140
86   2599001200  20141103T000000   305000         5       2.25         2660
87   3342103156  20140618T000000   461000         3       3.25         2770
91   5036300431  20150311T000000  1099880         5       2.75         3520
95   1483300570  20140908T000000   905000         4       2.50         3300
99   7338200240  20140516T000000   437500         3       2.50         2320
100  1952200240  20140611T000000   850830         3       2.50         2070
102  7214720075  20141212T000000   699950         3       2.25         2190
103  2450000295  20141007T000000  1088000         3       2.50         2920
105  1328310370  20150402T000000   375000         3       2.50         2340
108  1853000400  20150305T000000   680000         4       2.50         3140
109  3134100116  20140827T000000   470000         5       1.75         2030
110  9545230140  20140725T000000   597750         4       2.50         2310
113  6126500060  20141124T000000   329950         3       1.75         2080
114  8961960160  20141028T000000   480000         4       2.50         3230
120  7278700070  20150102T000000   660000         3       2.50         2400
123  3524049083  20141104T000000   445000         4       1.75         2100
124  3275860240  20140618T000000   770000         3       2.25         2910
125  4389200955  20150302T000000  1450000         4       2.75         2750
126  4058801670  20140717T000000   445000         3       2.25         2100
127  8732020310  20140717T000000   260000         4       2.25         2160
128  2331300505  20140613T000000   822500         5       3.50         2320
129  7853210060  20150406T000000   430000         4       2.50         2070
            ...              ...      ...       ...        ...          ...

     sqft_lot  floors  waterfront  view  condition  grade  sqft_above  \
1        7242     2.0           0     0          3      7        2170
10       9796     1.0           0     0          3      8        1860
15       5000     2.0           0     3          3      9        1980
21      44867     1.0           0     4          3      9        2330
22       6300     2.0           0     0          3      8        2270
24       6500     2.0           0     0          4      8        2450
26       2691     2.0           0     0          3      8        1750
29       7173     2.0           0     0          3      8        2570
30       3980     2.0           0     0          3      8        2320
32       5000     1.5           0     0          4      7        1510
34       6659     1.0           0     0          3      7        1280
35       3060     1.5           0     0          3      8        1510
37       6000     2.0           0     0          4      8        2360
39       7553     2.0           0     0          3      8        2620
40       5520     2.0           0     0          3      9        2570
42       5639     2.0           0     0          3      9        3595
45      13603     2.0           0     0          3      8        3160
47      13416     2.0           0     0          4      9        2290
49      65005     1.0           1     2          5      9        2165
51       9134     1.0           0     0          4      8        1640
54       6000     1.5           0     0          3      8        2130
55       5000     2.0           0     0          3      9        2830
56       4495     2.0           0     0          3      7        2250
57       4750     2.0           0     0          3      8        2420
58      14342     2.0           0     4          4      8        3250
60      21235     1.0           0     3          4      8        1590
62       8690     2.0           0     0          5      8        2519
65       3809     1.5           0     0          5      7        1770
66      11049     2.0           0     0          3     10        2720
67       4648     2.0           0     0          3      7        2240
69      20158     1.0           0     0          3      8        1600
72       7807     1.5           0     0          5      7        2250
73       5000     2.0           0     0          3      8        2380
75      35102     2.0           0     0          4     10        2390
79      39683     2.0           0     0          3     10        3450
80       5100     2.0           0     0          3      8        2350
82       6720     1.0           0     0          3      7        1010
85       3600     2.0           0     0          3      9        1900
86       8400     1.5           0     0          5      7        2660
87       6278     2.0           0     0          3      9        1980
91       6353     2.0           0     0          4     10        3520
95      10250     1.0           0     0          3      7        2390
99      36847     2.0           0     2          3      9        2320
100     13241     1.5           0     0          5      9        1270
102    107593     2.0           0     0          4      8        2190
103      8113     2.0           0     0          3      8        2920
105     10005     1.0           0     0          4      8        1460
108     28037     2.0           0     0          4     10        3140
109     12342     2.0           0     0          4      7        2030
110      9624     2.0           0     0          3      8        2310
113      5969     1.0           0     2          3      7        1080
114     16171     2.0           0     3          3      9        2520
120      6474     1.0           0     2          3      8        1560
123      4400     1.5           0     0          5      7        1720
124     10204     2.0           0     0          3      9        2910
125     17789     1.5           0     0          3      8        1980
126      8201     1.0           0     2          3      8        1620
127      8811     1.0           0     0          3      8        1360
128      4960     2.0           0     0          5      7        1720
129      4310     2.0           0     0          3      7        2070
          ...     ...         ...   ...        ...    ...         ...

     sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
1              400      1951          1991    98125  47.7210 -122.319
10            1700      1965             0    98007  47.6007 -122.145
15             970      1979             0    98126  47.5714 -122.375
21             720      1968             0    98040  47.5316 -122.233
22               0      1995             0    98092  47.3266 -122.169
24               0      1985             0    98030  47.3739 -122.172
26             700      1915             0    98119  47.6386 -122.360
29               0      2005             0    98052  47.7073 -122.110
30               0      2003             0    98027  47.5391 -122.070
32             820      1929             0    98117  47.6823 -122.368
34             780      1981             0    98058  47.4276 -122.157
35             790      1930          2002    98115  47.6827 -122.310
37               0      1904             0    98107  47.6702 -122.362
39               0      1996             0    98056  47.5301 -122.180
40               0      2000             0    98074  47.6145 -122.027
42               0      2014             0    98053  47.6848 -122.016
45               0      2003             0    98019  47.7443 -121.977
47               0      1981             0    98007  47.6194 -122.151
49             588      1953             0    98070  47.4041 -122.451
51            1510      1966             0    98056  47.4934 -122.189
54             600      1927             0    98105  47.6571 -122.281
55               0      1995             0    98105  47.6597 -122.290
56               0      2008             0    98042  47.3663 -122.114
57               0      2003             0    98042  47.3663 -122.122
58               0      1968             0    98008  47.5880 -122.116
60             560      1959             0    98166  47.4336 -122.339
62               0      1973             0    98166  47.4428 -122.344
65            1000      1925             0    98144  47.5747 -122.304
66               0      1989             0    98004  47.5815 -122.192
67               0      2005             0    98001  47.3378 -122.257
69            1600      1965             0    98004  47.6303 -122.215
72             500      1916             0    98125  47.7168 -122.287
73               0      2005             0    98038  47.3608 -122.036
75            1040      1986             0    98075  47.5822 -121.987
79               0      2002             0    98010  47.3420 -122.025
80               0      2003             0    98038  47.3512 -122.008
82            1010      1948             0    98118  47.5474 -122.291
85             240      1925             0    98119  47.6337 -122.365
86               0      1961             0    98092  47.2909 -122.189
87             790      2006             0    98056  47.5228 -122.199
91               0      2001             0    98199  47.6506 -122.391
95             910      1946          1991    98040  47.5873 -122.249
99               0      1992             0    98045  47.4838 -121.714
100            800      1910             0    98102  47.6415 -122.315
102              0      1983             0    98077  47.7731 -122.080
103              0      1950          2010    98004  47.5814 -122.196
105            880      1978             0    98058  47.4431 -122.133
108              0      1991             0    98077  47.7304 -122.082
109              0      1942             0    98052  47.6417 -122.109
110              0      1984             0    98027  47.5386 -122.053
113           1000      1971             0    98108  47.5474 -122.295
114            710      2001             0    98001  47.3183 -122.253
120            840      1964             0    98177  47.7728 -122.386
123            380      1924             0    98118  47.5299 -122.266
124              0      1990             0    98052  47.6897 -122.098
125            770      1914          1992    98004  47.6141 -122.212
126            480      1967             0    98178  47.5091 -122.244
127            800      1978             0    98023  47.3129 -122.390
128            600      1926             0    98103  47.6763 -122.352
129              0      2004             0    98065  47.5319 -121.850
               ...       ...           ...      ...      ...      ...

     sqft_living15
1             1690 ...
10            2210 ...
15            2140 ...
21            4110 ...
22            2240 ...
24            2200 ...
26            1760 ...
29            2630 ...
30            2580 ...
32            1460 ...
34            2020 ...
35            1590 ...
37            1730 ...
39            2620 ...
40            2470 ...
42            3625 ...
45            3050 ...
47            2680 ...
49            2680 ...
51            1990 ...
54            2730 ...
55            1950 ...
56            2250 ...
57            2690 ...
58            2960 ...
60            2570 ...
62            2500 ...
65            1440 ...
66            2750 ...
67            2221 ...
69            3390 ...
72            1510 ...
73            2420 ...
75            3240 ...
79            3350 ...
80            2350 ...
82            1720 ...
85            2020 ...
86            1590 ...
87            1900 ...
91            2520 ...
95            1950 ...
99            2550 ...
100           2200 ...
102           2570 ...
103           2370 ...
105           2250 ...
108           2990 ...
109           2500 ...
110           1940 ...
113           2090 ...
114           2640 ...
120           2340 ...
123           1850 ...
124           2700 ...
125           3060 ...
126           2660 ...
127           2090 ...
128           1700 ...
129           1970 ...
               ...

[9118 rows x 21 columns]

In [89]:
my_features = ['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'zipcode']
advanced_features = [
'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'zipcode',
'condition', # condition of house
'grade', # measure of quality of construction
'waterfront', # waterfront property
'view', # type of view
'sqft_above', # square feet above ground
'sqft_basement', # square feet in basement
'yr_built', # the year built
'yr_renovated', # the year renovated
'lat', 'long', # the lat-long of the parcel
'sqft_living15', # average sq.ft. of 15 nearest neighbors
'sqft_lot15', # average lot size of 15 nearest neighbors 
]

In [90]:
# Create linear regression object
regr1 = linear_model.LinearRegression()
regr2 = linear_model.LinearRegression()

In [91]:
splitter = np.random.rand(len(houses)) < 0.8

In [92]:
train_data = houses[splitter]
test_data = houses[~splitter]

In [97]:
regr1.fit(train_data[my_features], train_data['price'])
regr2.fit(train_data[advanced_features], train_data['price'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [98]:
print(regr1.coef_)
print(regr2.coef_)

[ -5.59282350e+04   1.30826235e+04   3.15778138e+02  -3.10334374e-01
  -3.96946114e+03   5.61059168e+02]
[ -3.42332478e+04   4.39079698e+04   1.08203673e+02   1.21000987e-01
   4.06518413e+03  -5.95003743e+02   2.82150447e+04   9.71515268e+04
   5.66284905e+05   5.16523843e+04   7.26769938e+01   3.55266799e+01
  -2.63447080e+03   1.39890196e+01   6.07444336e+05  -2.30855933e+05
   2.32553731e+01  -3.94340192e-01]

In [105]:
print("RMSE: %.2f"
      % np.sqrt(np.mean(regr1.predict(test_data[my_features])  - test_data['price'] ) ** 2))

print("RMSE_adv: %.2f"
      % np.sqrt(np.mean(regr2.predict(test_data[advanced_features]) - test_data['price']) ** 2))

RMSE: 3528.58
RMSE_adv: 5185.98

In [118]:
print(test_data['price'][0:2])
print(regr1.predict(test_data[my_features])[0:2])
print(regr2.predict(test_data[advanced_features])[0:2])

0     221900
5    1225000
Name: price, dtype: int64
[  323819.13361875  1552567.99549939]
[  207529.76225407  1461923.64028598]